networks:
  docs_agent:
    driver: bridge

services:
  qdrant:
    image: qdrant/qdrant:v1.14.0
    ports:
      - '6343:6333' # Qdrant HTTP port
      - '6344:6334' # Qdrant gRPC port
    volumes:
      - ../qdrant_docs/database:/qdrant/storage
    networks:
      - docs_agent

  postgres:
    image: postgres:16
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./app/.env
    networks:
      - docs_agent

  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"   # Management UI
    env_file:
      - ./app/.env
    networks:
      - docs_agent

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf      
    command: >
      sh -c "redis-server /usr/local/etc/redis/redis.conf"       
    networks:
      - docs_agent
    depends_on:
      - rabbitmq      

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./app/.env
    volumes:
      - .:/app
    networks:
      - docs_agent
    ports:
      - '8002:80'

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./app/.env
    command: >
      sh -c "celery -A app.celery_tasks.worker:app worker --loglevel=info"     
    volumes:
      - .:/app
    networks:
      - docs_agent
    depends_on:
      - qdrant
      - rabbitmq
      - redis
      - app

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c " pip install celery flower && celery -A app.celery_tasks.worker:app flower --port=5555"
    env_file:
      - ./app/.env
    ports:
      - 5555:5555
    depends_on:
      - app
      - worker
    networks:
      - docs_agent


volumes:
  qdrant_docs:
  postgres_data:
  redis_data: